# this is a makefile to compile the custom terminal that I have implemented

all:
	gcc main.c formatted_path.c other_commands.c custom_commands.c myls/myls.c myps/myps.c mycp_mv/mycp.c mygrep/mygrep.c man.c -lreadline -o myterminal.out

run:
	gcc main.c formatted_path.c other_commands.c custom_commands.c myls/myls.c myps/myps.c mycp_mv/mycp.c mygrep/mygrep.c man.c -lreadline -o myterminal.out
	./myterminal.out