# this is a makefile to compile the custom terminal that I have implemented

all:
	gcc main.c formatted_path.c other_commands.c -lreadline -o myterminal.out
run:
	gcc main.c formatted_path.c other_commands.c -lreadline -o myterminal.out
	./myterminal.out
